language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - pip install codecov
  - pip install pytest-cov
install:
  - "pip install -r requirements.txt"
script:
  - "py.test -v --cov"
after_success:
  - codecov
