language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - pip install codecov
  - pip install pytest-cov
  - pip install pytest-pep8
install:
  - "pip install -r requirements.txt"
script:
  - "py.test -v --cov --pep8"
after_success:
  - codecov
