language: python
python:
  - "2.6"
install:
  - "pip install -r requirements.txt"
script:
  - "python netcompare.py tests/sample1.conf tests/sample2.conf cisco"
  - "ansible-playbook -i ansible/example-inventory ansible/example-playbook.yml"
